### ISSUE TITLE
alipay composer install error: config files didn't exist under config directory.

### ISSUE THREAD

**Issue by IvanJobs** [Latrell/Alipay#2]
Hi bro,
Recently I created a laravel 5.1 project under /usr/share/nginx/laravel directory.
As I want to use latrel/alipay, so I run composer require latrell/alipya dev-master and composer install.
After that I didn't find config/latrell-alipay.php or other two config files under config directory, but vendor/latrell/alipay is ok. I don't know why, please help me, thx:)

**Comment by Latrell** [comment]
run the shell:

**Comment by IvanJobs** [comment]
@Latrell Thx, fixed my problem:)
