### ISSUE TITLE
>=php7.2 each()参数废除导致报错

### ISSUE THREAD

**Issue by canren** [Latrell/Alipay#30]
`private function paraFilter($para)`
`{`
`	$para_filter = array();`
`	while ((list ($key, $val) = each($para)) == true) {`
`		if ($key == 'sign' || $key == 'sign_type' || $val == '') {`
`			continue;`
`		} else {`
`			$para_filter[$key] = $para[$key];`
`		}`
`	}`
`	return $para_filter;`
`}`

上述代码 
`while ((list ($key, $val) = each($para)) == true) {` 
修改为 
`foreach ($para as $key => $val) { `
兼容性会更好 #32

**Comment by ibogood** [comment]
我精简了代码 修复了7.2的bug 基本上重写了
可以关注 ibogood/alipay 用法同此一样
